apiVersion: apps/v1
kind: Deployment
metadata:
  name: kindle-highlights
  labels:
    app: kindle-highlights
spec:
  selector:
    matchLabels:
      app: kindle-highlights
  template:
    metadata:
      labels:
        app: kindle-highlights
    spec:
      containers:
      - name: kindle-highlights
        image: frontend
        ports:
        - containerPort: 8001
